recent changes

diff --git a/bin/xmdev-rebuild b/bin/xmdev-rebuild
--- a/bin/xmdev-rebuild
+++ b/bin/xmdev-rebuild
@@ -1,18 +1,38 @@
-#!/bin/sh
+#!/bin/zsh
+
+header_color='\e[34m'
+clear_color='\e[0m'
 
 echo "Do you wish to rebuild xmdev (y/n)? "
 read answer
 
 if [ "$answer" != "${answer#[Yy]}" ] ;then
-    echo "\nMaking sure postres docker started ................." &&
+    echo -e "$header_color" &&
+    echo -e "\n-------------------------------------------------------------------------------------------------------"
+    echo -e "| Making sure postgres docker is started"
+    echo -e "-------------------------------------------------------------------------------------------------------"
+    echo -e "$clear_color" &&
     docker start postgres && sleep 10 &&
-    echo "\nApplying DB Patches ................." &&
+
+    echo -e "$header_color" &&
+    echo -e "\n-------------------------------------------------------------------------------------------------------" &&
+    echo -e "| Applying DB Patches" &&
+    echo -e "-------------------------------------------------------------------------------------------------------" &&
+    echo -e "$clear_color" &&
     cd ~/xm-database &&
     ./gradlew applyDbPatches &&
 
-    echo "\nRebuild onDemand ...................." &&
+    echo -e "$header_color" &&
+    echo -e "\n-------------------------------------------------------------------------------------------------------" &&
+    echo -e "| Rebuilding ondemand" &&
+    echo -e "-------------------------------------------------------------------------------------------------------" &&
+    echo -e "$clear_color" &&
     cd ~/ondemand &&
-    ./gradlew linkWebui
-    #./gradlew clean build -x test
+    #./gradlew linkWebui
+    ./gradlew clean build linkWebui -x test -x :react:reactUi:webpackDev -x :react:reactUi:lintJs
+
+    EXITCODE=$?
+    test $EXITCODE -eq 0 && echo "\n\n\e[32m>>> XMDEV REBUILD SUCCESS\n$clear_color" || echo "\n\n\e[31m>>> XMDEV REBUILD FAILED\n$clear_color";
+    exit $EXITCODE
 fi
 
diff --git a/bin/xmdev-update b/bin/xmdev-update
--- a/bin/xmdev-update
+++ b/bin/xmdev-update
@@ -1,17 +1,39 @@
-#!/bin/bash
+#!/bin/zsh
 
-read -p "Run git pull --rebase in xmdev projects? " -n 1 -r
-echo    # (optional) move to a new line
-if [[ $REPLY =~ ^[Yy]$ ]]
-then
-    cd ~/ondemand
+header_color='\e[34m'
+clear_color='\e[0m'
+
+echo "Run git pull --rebase in xmdev projects (y/n)? "
+read answer
+
+if [ "$answer" != "${answer#[Yy]}" ] ;then
+    echo -e "$header_color" &&
+    echo -e "\n-------------------------------------------------------------------------------------------------------" &&
+    echo -e "| ondemand" &&
+    echo -e "-------------------------------------------------------------------------------------------------------" &&
+    echo -e "$clear_color" &&
+    cd ~/ondemand &&
+    git pull --rebase &&
+
+    echo -e "$header_color" &&
+    echo -e "\n-------------------------------------------------------------------------------------------------------" &&
+    echo -e "| xm-database" &&
+    echo -e "-------------------------------------------------------------------------------------------------------" &&
+    echo -e "$clear_color" &&
+    cd ~/xm-database &&
+    git stash &&
+    git pull --rebase &&
+    git stash pop &&
+
+    echo -e "$header_color" &&
+    echo -e "\n-------------------------------------------------------------------------------------------------------" &&
+    echo -e "| xm-api" &&
+    echo -e "-------------------------------------------------------------------------------------------------------" &&
+    echo -e "$clear_color" &&
+    cd ~/xm-api &&
     git pull --rebase
 
-    cd ~/xm-database
-    git stash
-    git pull --rebase
-    git stash pop
-
-    cd ~/xm-api
-    git pull --rebase
+    EXITCODE=$?
+    test $EXITCODE -eq 0 && echo "\n\n\e[32m>>> XMDEV REBASE SUCCESS\n$clear_color" || echo "\n\n\e[31m>>> XMDEV REBASE FAILED\n$clear_color";
+    exit $EXITCODE
 fi
